# .streamlit/secrets.toml
# Streamlit Cloud 배포시 이 파일 내용을 Streamlit Cloud Secrets에 붙여넣으세요
# 이 파일은 절대 GitHub에 올리지 마세요!

ANTHROPIC_API_KEY = "여기에_Claude_API_키_입력"

[gcp_service_account]
type = "service_account"
project_id = "kb-dashboard-499704"
private_key_id = "JSON파일의_private_key_id값"
private_key = "JSON파일의_private_key값"
client_email = "kb-dashboard@kb-dashboard-499704.iam.gserviceaccount.com"
client_id = "103155350932676025223"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
